database:
  host: localhost
  port: 5432
  user: user
  password: passwd
  name: db

api:
  github:
    token: ""  # 需要填入您的 GitHub Token
  deepseek:
    api_key: "token"

app:
  search_keyword: "topic:ai"
  interval_hours: 24
  max_repos_per_page: 1
  port: 8080

log:
  level: info
  format: json
  output: file
  file:
    path: ./logs
    name: repoinsight.log
    max_size: 100
    max_backups: 10
    max_age: 30
    compress: true 