version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=repoinsight_user
      - DB_PASSWORD=K8p9m2n5x7Qw3
      - DB_NAME=repoinsight_db
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=repoinsight_user
      - POSTGRES_PASSWORD=K8p9m2n5x7Qw3
      - POSTGRES_DB=repoinsight_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  repoinsight-network:
    driver: bridge 